RESPOSTAS = [
    "iniciar",
    "dwaynejohnson", 
    "elizabeth", 
    "socrates", 
    "platao", 
    "euclides",
    "renedescartes",
    "thomasjefferson",
    "alberteinstein",
    "ronaldinhogaucho",
    "despertar",
    "aristoteles",
    "cleopatra",
    "nero",
    "johndrockefeller",
    "atila",
    "lutero",
    "gengiskhan",
    "maquiavel",
    "judas",
    "rihanna",
    "imperioromano",
    "wernerheisenberg",
    "federacaoanarquistagaucha",
    "cesarlattes",
    "delegadofleury",
    "enpassant",
    "ozymandias",
    "circunferencia",
    "vamoscolocarumsorrisonesserosto",
    "hamurabi",
    "ddd82",
    "inri",
    "meajude",
    "cachorrocaramelo",
    "aleijadinho",
    "independencia",
]

DICAS = [
    "",
    "Ator do filme JUMANJI!", 
    "Foi de Americanas ano passado!", 
    "Jogou muito no Corinthians!", 
    "Já foi um planeta né vida?!", 
    "Ano de nascimento e morte: Por volta de 300 a.C\nPaís de nascimento: Grécia",
    "Plano infálivel!",
    "Use o Google Lens!",
    "Tudo é relativo!",
    "Aquele que cantou com o Wesley Safadão!",
    "Resposta se encontra nas 9 anteriores",
    "Característica: Grego",
    "Característica: Cabelos escuros",
    "Característica: Cabelos curtos e encaracolados",
    "Característica: Empresário americano",
    "Característica: Alto e musculoso",
    "Característica: O reformador protestante ",
    "Característica: Teve muitos filhos",
    "Característica: Italiano ",
    "Característica: Perdeu as botas",
    "Pop",
    "Política",
    "Físico 1932",
    "Federação",
    "Físico Brasileiro",
    "Ditadura Militar",
    "Francês",
    "Watchmen",
    "Zoom máximo",
    "Davi",
    "O primeiro",
    "Sei contar, sei ler",
    "Pregado",
    "Ave, César!",
    "Na dançinha com ele",
    "Minha perna",
    "A PrOPóSiTo É O ÚLTIMO ENIGMA, SEM MAIS DICAS!",
]